<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vchalla-lenovo1" failures="0" tests="5" name="com.aequilibrium.selenium.Login_Tests" time="49.117" errors="1" timestamp="2021-08-10T23:22:02 PDT" skipped="0">
  <testcase classname="com.aequilibrium.selenium.Login_Tests" name="validateSuccessfullLogin" time="5.827"/>
  <system-out>
    <![CDATA[validateSuccessfullLogin - Passed]]>
  </system-out>
  <testcase classname="com.aequilibrium.selenium.Login_Tests" name="validateLogin_WithWrongPassword" time="5.585"/>
  <system-out>
    <![CDATA[Wrong Password validation - PASSED]]>
  </system-out>
  <testcase classname="com.aequilibrium.selenium.Login_Tests" name="validateLogin_ForLockedOutUser" time="4.244"/>
  <system-out>
    <![CDATA[Lockedout user validation - PASSED]]>
  </system-out>
  <testcase classname="com.aequilibrium.selenium.Login_Tests" name="validateLogin_UserNameAsBlank" time="3.906"/>
  <system-out>
    <![CDATA[Username blank validation - PASSED]]>
  </system-out>
  <testcase classname="com.aequilibrium.selenium.Login_Tests" name="validateLogin_PasswordAsBlank" time="29.555">
    <error message="Expected condition failed: waiting for presence of element located by: By.xpath: //div[@class=&#039;error-message-container error&#039;]/h3[contains(text(),&#039;Username is required&#039;)] (tried for 25 second(s) with 500 milliseconds interval)" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Expected condition failed: waiting for presence of element located by: By.xpath: //div[@class='error-message-container error']/h3[contains(text(),'Username is required')] (tried for 25 second(s) with 500 milliseconds interval)
at com.aequilibrium.selenium.Login_Tests.validateLogin_PasswordAsBlank(Login_Tests.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateLogin_PasswordAsBlank -->
  <system-out/>
</testsuite> <!-- com.aequilibrium.selenium.Login_Tests -->
